---
- hosts: dreamteam
  user: sorsby
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
  tasks:
  - name: ensure pip is installed
    apt:
      name: python-pip
      state: latest
  - name: ensure nginx is at the latest version
    apt:
      name: nginx
      state: latest
  - name: ensure git is at the latest version
    apt:
      name: git
      state: latest
  - name: copy dreamteam.conf to server
    copy:
      src: dreamteam.conf
      dest: /etc/nginx/conf.d/dreamteam.conf
  - name: Create symbolic link to sites available from conf
    file:
      src: /etc/nginx/conf.d/dreamteam.conf
      dest: /etc/nginx/sites-available/dreamteam.conf
      state: link
  - name: Create symbolic link to sites enabled from conf
    file:
      src: /etc/nginx/sites-available/dreamteam.conf
      dest: /etc/nginx/sites-enabled/dreamteam.conf
      state: link
  - name: clone the git repository to the server
    become: no
    git:
      repo: git@github.com:glossopm/dream-team-project.git
      clone: yes
      dest: ~/www/
      force: yes
      version: master
  - name: start the nginx service
    service:
      name: nginx
      state: started
  - name:
    pip:
      name: PrettyTable
      state: latest
  - name:
    pip:
      name: flask
      state: latest
  - name:
    pip:
      name: flask_wtf
      state: latest
  - name:
    pip:
      name: flask_nav
      state: latest
  - name: start daemon with flask app
    become_user: sorsby
    shell: nohup python ~/www/table-tennis-ladder/main.py &
    args:
      chdir: ~/www/table-tennis-ladder/
  - name: re-start the nginx service
    service:
      name: nginx
      state: restarted